add initial dall-e-3 support
steamship-plugins/dall-e pull request #3
Opened 2023-11-08 00:52 UTC by douglas-reid

2023-11-08 13:13 UTC, dkolas requested changes
Looking good!  One requested fix around model override.

2023-11-08 13:13 UTC, dkolas commented on src/api.py
> +            inputs = self._inputs_from_config_and_runtime_params(options)
issue (blocking): For billing purposes, we should not allow the 'model' field to be overridden by options.

2023-11-08 13:13 UTC, dkolas commented on src/api.py
> +            return v
praise: So fancy!

2023-11-15 18:06 UTC, douglas-reid commented on src/api.py
> +            inputs = self._inputs_from_config_and_runtime_params(options)
is this because we don't preserve options in UsageReports?  Is that a potential feature request?

it looks like the `gpt-4` plugin allows similar runtime overriding -- should we fix that too?

2023-11-17 19:23 UTC, dkolas commented on src/api.py
> +            inputs = self._inputs_from_config_and_runtime_params(options)
Yes, runtime options are not considered at all when applying pricing rows.  It's just the plugin and its configuration.  

I recently changed the gpt-4 plugin to not allow overriding of model in runtime options for this reason.

2023-11-17 19:54 UTC, douglas-reid commented on src/api.py
> +            inputs = self._inputs_from_config_and_runtime_params(options)
done.

2023-11-17 20:01 UTC, dkolas approved these changes

2023-11-17 20:03 UTC, merged